addSbtPlugin("com.47deg"  % "sbt-microsites" % "1.3.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.5")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.codacy" % "sbt-codacy-coverage" % "3.0.3")
addSbtPlugin("io.gatling" % "gatling-sbt" % "3.1.3")
addSbtPlugin("io.kamon" % "sbt-kanela-runner" % "2.0.7")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.6")