addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.11")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.6")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.8.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("com.codacy" % "sbt-codacy-coverage" % "1.3.15")
addSbtPlugin("io.gatling" % "gatling-sbt" % "3.0.0")
